# Introduction to Pandas

- Pandas Python ki ek powerful library hai jo data ko handle aur analyze karne ke liye use hoti hai.

- Data read karne deta hai (CSV, Excel, etc.)

- Data clean karne deta hai

- Data filter aur analyze karne deta hai

- Statistical operations perform karne deta hai

# Installation Process
- pip install pandas

# Pandas ke 2 main data structures

# 1: Series

#### Series = 1D labeled array

In [2]:
import pandas as pd

# Simple Series
s = pd.Series([10, 20, 30, 40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
s = pd.Series([10, 20, 30], index=["a", "b", "c"])
print(s)

a    10
b    20
c    30
dtype: int64

In [4]:
print(s["a"])

10

# DataFrame

#### DataFrame = 2D table (rows + columns)

In [5]:
data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Marks": [85, 90, 78],
    "City": ["Lahore", "Karachi", "Islamabad"]
}

df = pd.DataFrame(data)
print(df)

    Name  Marks       City
0    Ali     85     Lahore
1   Sara     90    Karachi
2  Ahmed     78  Islamabad

# Data Input

# Read From Excel

In [11]:
df = pd.read_excel("practice_for_power_bi.xlsx")

ValueError: Excel file format cannot be determined, you must specify an engine manually.

# Read From csv

In [3]:
import pandas as pd
df = pd.read_csv("synthetic_mobile_sales_2025.csv")

In [4]:
df.head()

,Sale_ID,Brand,Model,Country,Storage,Color,Price_USD,Units_Sold,Revenue_USD,Customer_Rating,Payment_Method,Sale_Month,Sale_Year
0,1,Realme,Realme Model 2,UK,512GB,Gold,656,20,13120,3.7,Installments,11,2025
1,2,Vivo,Vivo Model 20,Australia,512GB,Blue,1013,9,9117,3.7,Debit Card,2,2025
2,3,Motorola,Motorola Model 12,Germany,512GB,White,1471,7,10297,3.1,Credit Card,2,2025
3,4,Vivo,Vivo Model 13,USA,512GB,Gold,1220,19,23180,3.6,Debit Card,6,2025
4,5,Vivo,Vivo Model 15,UAE,128GB,Silver,375,8,3000,4.4,Online Payment,1,2025

# Selection & Indexing

In [8]:
df[['Brand']]

        Brand
0      Realme
1        Vivo
2    Motorola
3        Vivo
4        Vivo
..        ...
495   OnePlus
496    Xiaomi
497      Vivo
498   Samsung
499    Xiaomi

[500 rows x 1 columns]

In [9]:
df['Brand'] # Selecting Single Column

0        Realme
1          Vivo
2      Motorola
3          Vivo
4          Vivo
         ...
495     OnePlus
496      Xiaomi
497        Vivo
498     Samsung
499      Xiaomi
Name: Brand, Length: 500, dtype: str

In [6]:
df['Brand','Sale_ID']

KeyError: ('Brand', 'Sale_ID')

In [7]:
df[['Brand','Sale_ID']] #Selecting multiple columns

        Brand  Sale_ID
0      Realme        1
1        Vivo        2
2    Motorola        3
3        Vivo        4
4        Vivo        5
..        ...      ...
495   OnePlus      496
496    Xiaomi      497
497      Vivo      498
498   Samsung      499
499    Xiaomi      500

[500 rows x 2 columns]

In [10]:
df.loc[0]

Sale_ID                         1
Brand                      Realme
Model              Realme Model 2
Country                        UK
Storage                     512GB
Color                        Gold
Price_USD                     656
Units_Sold                     20
Revenue_USD                 13120
Customer_Rating               3.7
Payment_Method       Installments
Sale_Month                     11
Sale_Year                    2025
Name: 0, dtype: object

In [12]:
df.iloc[0]        # First row

Sale_ID                         1
Brand                      Realme
Model              Realme Model 2
Country                        UK
Storage                     512GB
Color                        Gold
Price_USD                     656
Units_Sold                     20
Revenue_USD                 13120
Customer_Rating               3.7
Payment_Method       Installments
Sale_Month                     11
Sale_Year                    2025
Name: 0, dtype: object

In [15]:
df.iloc[0:1]      # First 1 rows [staring index:ending index]

,Sale_ID,Brand,Model,Country,Storage,Color,Price_USD,Units_Sold,Revenue_USD,Customer_Rating,Payment_Method,Sale_Month,Sale_Year
0,1,Realme,Realme Model 2,UK,512GB,Gold,656,20,13120,3.7,Installments,11,2025

In [18]:
df.loc[0, "Brand"]      # Row 0, Name column

'Realme'

In [20]:
df.iloc[0, 2]          # Row 1, Column index 2

'Realme Model 2'

In [21]:
df[df["Price_USD"] > 80]

,Sale_ID,Brand,Model,Country,Storage,Color,Price_USD,Units_Sold,Revenue_USD,Customer_Rating,Payment_Method,Sale_Month,Sale_Year
0,1,Realme,Realme Model 2,UK,512GB,Gold,656,20,13120,3.7,Installments,11,2025
1,2,Vivo,Vivo Model 20,Australia,512GB,Blue,1013,9,9117,3.7,Debit Card,2,2025
2,3,Motorola,Motorola Model 12,Germany,512GB,White,1471,7,10297,3.1,Credit Card,2,2025
3,4,Vivo,Vivo Model 13,USA,512GB,Gold,1220,19,23180,3.6,Debit Card,6,2025
4,5,Vivo,Vivo Model 15,UAE,128GB,Silver,375,8,3000,4.4,Online Payment,1,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,OnePlus,OnePlus Model 5,UK,128GB,Blue,371,10,3710,3.5,Debit Card,6,2025
496,497,Xiaomi,Xiaomi Model 4,Canada,128GB,Gold,414,8,3312,5.0,Installments,7,2025
497,498,Vivo,Vivo Model 9,Pakistan,256GB,Blue,314,17,5338,4.6,Cash,7,2025
498,499,Samsung,Samsung Model 19,France,128GB,Gold,342,1,342,4.5,Cash,6,2025
499,500,Xiaomi,Xiaomi Model 14,UK,64GB,Gold,1457,4,5828,3.2,Installments,9,2025

In [22]:
df[(df["Price_USD"] > 80) & (df["Country"] == "UK")]

,Sale_ID,Brand,Model,Country,Storage,Color,Price_USD,Units_Sold,Revenue_USD,Customer_Rating,Payment_Method,Sale_Month,Sale_Year
0,1,Realme,Realme Model 2,UK,512GB,Gold,656,20,13120,3.7,Installments,11,2025
9,10,Huawei,Huawei Model 6,UK,512GB,Gold,921,2,1842,4.8,Cash,3,2025
27,28,Huawei,Huawei Model 17,UK,256GB,Green,1395,6,8370,4.5,Credit Card,12,2025
53,54,Huawei,Huawei Model 8,UK,512GB,Silver,1409,1,1409,4.1,Installments,7,2025
74,75,Motorola,Motorola Model 6,UK,256GB,Green,754,8,6032,4.9,Credit Card,1,2025
77,78,Realme,Realme Model 5,UK,256GB,Blue,908,7,6356,4.6,Credit Card,2,2025
98,99,Google,Google Model 15,UK,512GB,Black,383,12,4596,4.8,Cash,7,2025
130,131,Google,Google Model 16,UK,512GB,Green,1088,7,7616,3.6,Online Payment,3,2025
139,140,OnePlus,OnePlus Model 7,UK,128GB,Gold,1482,10,14820,4.6,Cash,6,2025
149,150,Oppo,Oppo Model 7,UK,256GB,Gold,1118,7,7826,4.7,Cash,5,2025
154,155,Oppo,Oppo Model 7,UK,256GB,Green,1240,2,2480,4.1,Installments,8,2025
166,167,Oppo,Oppo Model 3,UK,512GB,Green,460,12,5520,3.6,Installments,11,2025
179,180,Realme,Realme Model 12,UK,512GB,Gold,477,7,3339,4.5,Credit Card,6,2025
186,187,Apple,Apple Model 13,UK,256GB,Blue,1279,16,20464,4.9,Debit Card,3,2025
189,190,Realme,Realme Model 8,UK,256GB,Green,361,1,361,3.8,Credit Card,8,2025
204,205,Apple,Apple Model 14,UK,128GB,White,322,6,1932,4.0,Installments,9,2025
206,207,Samsung,Samsung Model 19,UK,64GB,Silver,1198,6,7188,3.8,Cash,6,2025
225,226,Motorola,Motorola Model 8,UK,512GB,Gold,1115,15,16725,4.2,Credit Card,12,2025
231,232,Oppo,Oppo Model 3,UK,64GB,White,1084,3,3252,3.6,Installments,12,2025
235,236,Huawei,Huawei Model 12,UK,128GB,Silver,917,16,14672,3.6,Cash,8,2025
265,266,Motorola,Motorola Model 20,UK,64GB,Silver,1087,18,19566,3.5,Online Payment,9,2025
282,283,Apple,Apple Model 18,UK,128GB,Gold,1406,9,12654,3.1,Online Payment,9,2025
289,290,Oppo,Oppo Model 19,UK,64GB,White,1022,19,19418,4.2,Credit Card,5,2025
305,306,Google,Google Model 6,UK,256GB,Silver,480,18,8640,5.0,Debit Card,9,2025
310,311,Google,Google Model 12,UK,64GB,Gold,1058,4,4232,4.5,Debit Card,2,2025
315,316,Motorola,Motorola Model 18,UK,256GB,Black,539,1,539,3.7,Online Payment,10,2025
328,329,Oppo,Oppo Model 3,UK,64GB,Gold,1215,6,7290,4.6,Debit Card,6,2025
339,340,Apple,Apple Model 19,UK,128GB,White,1236,13,16068,4.6,Installments,6,2025
346,347,Motorola,Motorola Model 14,UK,128GB,White,528,20,10560,3.4,Installments,8,2025
351,352,OnePlus,OnePlus Model 7,UK,128GB,Black,1481,12,17772,3.1,Installments,10,2025
353,354,Google,Google Model 18,UK,128GB,Blue,1412,5,7060,3.8,Installments,2,2025
357,358,Apple,Apple Model 3,UK,64GB,White,826,9,7434,3.5,Installments,4,2025
368,369,Samsung,Samsung Model 5,UK,256GB,Black,715,4,2860,4.6,Debit Card,8,2025
369,370,Vivo,Vivo Model 7,UK,128GB,Gold,1310,1,1310,4.2,Cash,8,2025
371,372,Google,Google Model 17,UK,64GB,Gold,1284,17,21828,3.6,Online Payment,9,2025
384,385,Huawei,Huawei Model 5,UK,256GB,Silver,384,14,5376,4.0,Debit Card,2,2025
391,392,Samsung,Samsung Model 5,UK,128GB,Gold,1000,9,9000,4.7,Online Payment,8,2025
396,397,Xiaomi,Xiaomi Model 19,UK,64GB,White,1449,9,13041,3.8,Installments,7,2025
401,402,Oppo,Oppo Model 14,UK,64GB,Gold,569,9,5121,4.5,Debit Card,7,2025
407,408,Huawei,Huawei Model 5,UK,128GB,Blue,713,15,10695,4.8,Debit Card,2,2025
409,410,Realme,Realme Model 17,UK,128GB,Green,1227,6,7362,3.5,Credit Card,8,2025
410,411,Xiaomi,Xiaomi Model 17,UK,64GB,Gold,648,19,12312,4.4,Credit Card,4,2025
411,412,Motorola,Motorola Model 7,UK,128GB,Gold,574,5,2870,4.8,Debit Card,9,2025
431,432,Oppo,Oppo Model 7,UK,512GB,Silver,336,20,6720,4.8,Cash,8,2025
447,448,Xiaomi,Xiaomi Model 3,UK,512GB,Blue,1109,16,17744,4.1,Credit Card,8,2025
456,457,Motorola,Motorola Model 15,UK,64GB,Silver,538,3,1614,4.4,Online Payment,5,2025
461,462,Oppo,Oppo Model 5,UK,64GB,Green,772,14,10808,4.5,Cash,3,2025
478,479,Vivo,Vivo Model 8,UK,256GB,Black,729,6,4374,4.4,Online Payment,5,2025
495,496,OnePlus,OnePlus Model 5,UK,128GB,Blue,371,10,3710,3.5,Debit Card,6,2025
499,500,Xiaomi,Xiaomi Model 14,UK,64GB,Gold,1457,4,5828,3.2,Installments,9,2025

-------------------------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------------------------------------------------------

In [23]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ali", "Sara"],
    "Marks": [85, 90, 78, 85, None],
    "City": ["Lahore", "Karachi", "Islamabad", "Lahore", "Karachi"]
}

df = pd.DataFrame(data)
print(df)

    Name  Marks       City
0    Ali   85.0     Lahore
1   Sara   90.0    Karachi
2  Ahmed   78.0  Islamabad
3    Ali   85.0     Lahore
4   Sara    NaN    Karachi

In [25]:
df.head(2)

   Name  Marks     City
0   Ali   85.0   Lahore
1  Sara   90.0  Karachi

In [26]:
df["Name"].unique()

<StringArray>
['Ali', 'Sara', 'Ahmed']
Length: 3, dtype: str

In [27]:
df["Name"].value_counts()

Name
Ali      2
Sara     2
Ahmed    1
Name: count, dtype: int64

In [29]:
df.columns

Index(['Name', 'Marks', 'City'], dtype='str')

In [30]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [31]:
df.sort_values("Marks")

    Name  Marks       City
2  Ahmed   78.0  Islamabad
0    Ali   85.0     Lahore
3    Ali   85.0     Lahore
1   Sara   90.0    Karachi
4   Sara    NaN    Karachi

In [32]:
df.sort_values("Marks", ascending=False)

    Name  Marks       City
1   Sara   90.0    Karachi
0    Ali   85.0     Lahore
3    Ali   85.0     Lahore
2  Ahmed   78.0  Islamabad
4   Sara    NaN    Karachi

In [35]:
df.sort_values(["City", "Marks"])

    Name  Marks       City
2  Ahmed   78.0  Islamabad
1   Sara   90.0    Karachi
4   Sara    NaN    Karachi
0    Ali   85.0     Lahore
3    Ali   85.0     Lahore

In [36]:
df.isnull()

    Name  Marks   City
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False   True  False

In [37]:
df.isnull().sum()

Name     0
Marks    1
City     0
dtype: int64

In [38]:
df.dropna()

    Name  Marks       City
0    Ali   85.0     Lahore
1   Sara   90.0    Karachi
2  Ahmed   78.0  Islamabad
3    Ali   85.0     Lahore

In [40]:
df["Marks"].fillna(10, inplace=True)

C:\Users\TroubleMaker\AppData\Local\Temp\ipykernel_18024\2208821426.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Marks"].fillna(10, inplace=True)

0    85.0
1    90.0
2    78.0
3    85.0
4    10.0
Name: Marks, dtype: float64

In [41]:
df["City"].replace("Lahore", "LHR")

0          LHR
1      Karachi
2    Islamabad
3          LHR
4      Karachi
Name: City, dtype: str

In [42]:
df.replace({"Lahore": "LHR", "Karachi": "KHI"})

    Name  Marks       City
0    Ali   85.0        LHR
1   Sara   90.0        KHI
2  Ahmed   78.0  Islamabad
3    Ali   85.0        LHR
4   Sara    NaN        KHI

In [43]:
# Dropping Column
df.drop("City", axis=1)

    Name  Marks
0    Ali   85.0
1   Sara   90.0
2  Ahmed   78.0
3    Ali   85.0
4   Sara    NaN

In [45]:
#Dropping Rows
df.drop(0)

    Name  Marks       City
1   Sara   90.0    Karachi
2  Ahmed   78.0  Islamabad
3    Ali   85.0     Lahore
4   Sara    NaN    Karachi

In [46]:
df.drop("City", axis=1, inplace=True)

In [47]:
df.head()

    Name  Marks
0    Ali   85.0
1   Sara   90.0
2  Ahmed   78.0
3    Ali   85.0
4   Sara    NaN

In [48]:
df.rename(columns={"Marks": "Score"}) # Rename the Columns

    Name  Score
0    Ali   85.0
1   Sara   90.0
2  Ahmed   78.0
3    Ali   85.0
4   Sara    NaN

In [49]:
df["Pass"] = df["Marks"] > 50 # Adding new Column

# Missing Values/Data

- Jab kisi dataset me koi value available na ho to usay missing value kehte hain.

Pandas me missing value ko:

- NaN (Not a Number)

- None

se represent kiya jata hai.

In [66]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Ali", "Sara", "Ahmed", "Hina"],
    "Marks": [85, np.nan, 78, None],
    "City": ["Lahore", "Karachi", None, "Islamabad"]
}

df = pd.DataFrame(data)
print(df)

    Name  Marks       City
0    Ali   85.0     Lahore
1   Sara    NaN    Karachi
2  Ahmed   78.0        NaN
3   Hina    NaN  Islamabad

In [52]:
df.isnull()

    Name  Marks   City
0  False  False  False
1  False   True  False
2  False  False   True
3  False   True  False

In [55]:
df.isnull().sum()

Name     0
Marks    2
City     1
dtype: int64

In [57]:
df.dropna()

  Name  Marks    City
0  Ali   85.0  Lahore

In [59]:
df.dropna(subset=["Marks"]) # agar specific column ky basis per krna ho tu

    Name  Marks    City
0    Ali   85.0  Lahore
2  Ahmed   78.0     NaN

- axis=1 → column
- axis=0 → row

In [60]:
df.dropna(axis=1)

    Name
0    Ali
1   Sara
2  Ahmed
3   Hina

# Filling Missing Values

### 1: Fixed Value Se Fill

In [61]:
df["Marks"].fillna(0, inplace=True)

C:\Users\TroubleMaker\AppData\Local\Temp\ipykernel_18024\302797634.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Marks"].fillna(0, inplace=True)

0    85.0
1     0.0
2    78.0
3     0.0
Name: Marks, dtype: float64

### 2: Mean Se Fill

In [62]:
df["Marks"].fillna(df["Marks"].mean(), inplace=True)

C:\Users\TroubleMaker\AppData\Local\Temp\ipykernel_18024\1389251290.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Marks"].fillna(df["Marks"].mean(), inplace=True)

0    85.0
1    81.5
2    78.0
3    81.5
Name: Marks, dtype: float64

### 3: Median Se Fill

In [63]:
df["Marks"].fillna(df["Marks"].median(), inplace=True)

C:\Users\TroubleMaker\AppData\Local\Temp\ipykernel_18024\3150800626.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Marks"].fillna(df["Marks"].median(), inplace=True)

0    85.0
1    81.5
2    78.0
3    81.5
Name: Marks, dtype: float64

### 4: Mode Se Fill (Categorical Data)

In [64]:
df["City"].fillna(df["City"].mode()[0], inplace=True)

C:\Users\TroubleMaker\AppData\Local\Temp\ipykernel_18024\442806574.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["City"].fillna(df["City"].mode()[0], inplace=True)

0       Lahore
1      Karachi
2    Islamabad
3    Islamabad
Name: City, dtype: str

### 5: Forward Fill (Previous Value Copy)

In [70]:
# df.fillna(method="ffill", inplace=True)
df.ffill(inplace=True)

    Name  Marks       City
0    Ali   85.0     Lahore
1   Sara   85.0    Karachi
2  Ahmed   78.0    Karachi
3   Hina   78.0  Islamabad

### 6: Backward Fill

In [71]:
df.bfill(inplace=True)

    Name  Marks       City
0    Ali   85.0     Lahore
1   Sara   85.0    Karachi
2  Ahmed   78.0    Karachi
3   Hina   78.0  Islamabad